export const BRANDLIST_FETCH_START = "BRANDLIST_FETCH_START";
export const BRANDLIST_FETCH_SUCCESS = "BRANDLIST_FETCH_SUCCESS";
export const BRANDLIST_FETCH_ERROR = "BRANDLIST_FETCH_ERROR";

export const BRAND_FETCH_START = "BRAND_FETCH_START";
export const BRAND_FETCH_SUCCESS = "BRAND_FETCH_SUCCESS";
export const BRAND_FETCH_FAIL = "BRAND_FETCH_FAIL";

export const BRAND_TOGGLEVERIFY_START = "BRAND_TOGGLEVERIFY_START";
export const BRAND_TOGGLEVERIFY_SUCCESS = "BRAND_TOGGLEVERIFY_SUCCESS";
export const BRAND_TOGGLEVERIFY_FAIL = "BRAND_TOGGLEVERIFY_FAIL";

export const DELETE_BRAND_START = "DELETE_BRAND_START";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAIL = "DELETE_BRAND_FAIL";
export const DELETE_BRAND_RESET = "DELETE_BRAND_RESET";

export const CREATE_BRAND_START = "CREATE_BRAND_START";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAIL = "CREATE_BRAND_FAIL";
export const CREATE_BRAND_RESET = "CREATE_BRAND_RESET";

export const EDIT_BRAND_START = "EDIT_BRAND_START";
export const EDIT_BRAND_SUCCESS = "EDIT_BRAND_SUCCESS";
export const EDIT_BRAND_FAIL = "EDIT_BRAND_FAIL";
export const EDIT_BRAND_RESET = "EDIT_BRAND_RESET";
