export const USER_CONTACT_START = "USER_CONTACT_START";
export const USER_CONTACT_SUCCESS = "USER_CONTACT_SUCCESS";
export const USER_CONTACT_FAIL = "USER_CONTACT_FAIL";
export const USER_CONTACT_REST = "USER_CONTACT_REST";
