export const NEWSLETTER_START = "NEWSLETTER_START";
export const NEWSLETTER_SUCCESS = "NEWSLETTER_SUCCESS";
export const NEWSLETTER_FAIL = "NEWSLETTER_FAIL";
export const NEWSLETTER_REST = "NEWSLETTER_REST";
