export const PRODUCTLIST_FETCH_START = "PRODUCTLIST_FETCH_START";
export const PRODUCTLIST_FETCH_SUCCESS = "PRODUCTLIST_FETCH_SUCCESS";
export const PRODUCTLIST_FETCH_ERROR = "PRODUCTLIST_FETCH_ERROR";
